services:
  app:
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    devices:
      - /dev/tpmrm0
    command: sleep infinity
    network_mode: host
    environment:
      # TCTI: device:/dev/tpm0
      TPM2TOOLS_TCTI: mssim:host=localhost,port=2321
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G

  tpm:
    image: tpmdev/tpm2-runtime
    network_mode: host
    restart: unless-stopped
    environment:
      TPM2TOOLS_TCTI: mssim:host=localhost,port=2321
    command: /bin/bash -c "tpm_server >/dev/null & sleep 1; tpm2_startup -c; sleep infinity"

